apiVersion: 1

datasources:
  - name: InfluxDB-k6
    uid: influxdb-k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    isDefault: true
    editable: false
    jsonData:
      httpMode: GET
  - name: Prometheus-Docker
    uid: prometheus-docker
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
